name: Test

on: [push]

jobs:
  test:
    name: Test on destination ${{ matrix.configurations.destination }}
    runs-on: macOS-latest
    strategy:
      matrix:
        configurations:
          - destination: "platform=macOS"
            scheme: "Fetch-macOS"
            platform: "macOS"
          - destination: "platform=macOS"
            scheme: "Fetch-macOS"
            platform: "macOS"
          - destination: "platform=macOS"
            scheme: "Fetch-macOS"
            platform: "macOS"                        
        # destination: ["platform=macOS", "platform=iOS Simulator,name=iPhone 8", "platform=tvOS Simulator,name=Apple TV"]
        # scheme: ["Fetch-macOS", "Fetch-iOS", "Fetch-tvOS"]
        # platform: ["macOS", "iOS", "tvOS"]
    
    steps:
    - uses: actions/checkout@v1
    - name: Check version
      run: xcodebuild -version
    - name: Carthage
      run: carthage update --platform "${{ matrix.configurations.platform }}" --no-use-binaries
    - name: Run tests on ${{ matrix.configurations.destination }}
      run: xcodebuild -destination "${{ matrix.configurations.destination }}" -scheme "${{ matrix.configurations.scheme }}" test
